#pragma once
#include <string>
#include <vector>
// enum class classNames
//{
//    invalid = 0,
//    person,
//    bicycle,
//    car,
//    motorcycle,
//    airplane,
//    bus,
//    train,
//    truck,
//    boat,
//    traffic_light,
//    fire_hydrant,
//    street_sign,
//    stop_sign,
//    parking_meter,
//    bench,
//    bird,
//    cat,
//    dog,
//    horse,
//    sheep,
//    cow,
//    elephant,
//    bear,
//    zebra,
//    giraffe,
//    hat,
//    backpack,
//    umbrella,
//    shoe,
//    eye_glasses,
//    handbag,
//    tie,
//    suitcase,
//    frisbee,
//    skis,
//    snowboard,
//    sports_ball,
//    kite,
//    baseball_bat,
//    baseball_glove,
//    skateboard,
//    surfboard,
//    tennis_racket,
//    bottle,
//    plate,
//    wine_glass,
//    cup,
//    fork,
//    knife,
//    spoon,
//    bowl,
//    banana,
//    apple,
//    sandwich,
//    orange,
//    broccoli,
//    carrot,
//    hot_dog,
//    pizza,
//    donut,
//    cake,
//    chair,
//    couch,
//    potted_plant,
//    bed,
//    mirror,
//    dining_table,
//    window,
//    desk,
//    toilet,
//    door,
//    tv,
//    laptop,
//    mouse,
//    remote,
//    keyboard,
//    cell_phone,
//    microwave,
//    oven,
//    toaster,
//    sink,
//    refrigerator,
//    blender,
//    book,
//    clock,
//    vase,
//    scissors,
//    teddy_bear,
//    hair_drier,
//    toothbrush,
//    hair_brush,
//
//
//    last
//
//};
namespace myClassNames
{
const std::vector<std::string> classNames = {
    "person",       "bicycle",      "car",           "motorcycle",    "airplane",
    "bus",          "train",        "truck",         "boat",          "traffic light",
    "fire hydrant", "street sign",  "stop sign",     "parking meter", "bench",
    "bird",         "cat",          "dog",           "horse",         "sheep",
    "cow",          "elephant",     "bear",          "zebra",         "giraffe",
    "hat",          "backpack",     "umbrella",      "shoe",          "eye glasses",
    "handbag",      "tie",          "suitcase",      "frisbee",       "skis",
    "snowboard",    "sports ball",  "kite",          "baseball bat",  "baseball glove",
    "skateboard",   "surfboard",    "tennis racket", "bottle",        "plate",
    "wine glass",   "cup",          "fork",          "knife",         "spoon",
    "bowl",         "banana",       "apple",         "sandwich",      "orange",
    "broccoli",     "carrot",       "hot dog",       "pizza",         "donut",
    "cake",         "chair",        "couch",         "potted plant",  "bed",
    "mirror",       "dining table", "window",        "desk",          "toilet",
    "door",         "tv",           "laptop",        "mouse",         "remote",
    "keyboard",     "cell phone",   "microwave",     "oven",          "toaster",
    "sink",         "refrigerator", "blender",       "book",          "clock",
    "vase",         "scissors",     "teddy bear",    "hair drier",    "toothbrush",
    "hair brush"};
}